services:
  consul:
    image: hashicorp/consul:1.22.5
    container_name: consul-mba
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - mba-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      timeout: 2s
      interval: 5s
      retries: 5

  consul-config-loader:
    image: curlimages/curl:8.18.0
    container_name: consul-config-loader-mba
    depends_on:
      consul:
        condition: service_healthy
    volumes:
      - ./infra/config-repo:/config
      - ./infra/consul-loader/load-config.sh:/load-config.sh
    entrypoint: [ "/bin/sh", "/load-config.sh" ]
    networks:
      - mba-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    container_name: keycloak-mba
    ports:
      - "9090:8080"
    command: ["start-dev", "--import-realm"]
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./infra/keycloak-init:/opt/keycloak/data/import
    networks:
      - mba-net
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n' >&3; grep 'HTTP/1.1 200 OK' <&3"]
      timeout: 2s
      interval: 10s
      retries: 5

  postgres:
    image: postgres:18.3
    container_name: postgres-mba
    ports:
      - "5432:5432"
    networks:
      - mba-net
    environment:
      POSTGRES_MULTIPLE_DATABASES: accounts_db
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - ./infra/database-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -q -d postgres -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  gateway-server:
    build: infra/gateway-server
    container_name: mba-gateway-server
    depends_on:
      consul:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - mba-net
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "server.port":8080,
          "spring.cloud.consul.host":"consul",
          "spring.cloud.consul.port":8500,
          "security.oauth2.client.provider.keycloak.issuer-uri":"http://keycloak:8080/realms/mba" 
        }
    healthcheck:
      test: "curl --fail --silent gateway-server:8080/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 10s
      retries: 5

  accounts:
    build: core/accounts
    container_name: mba-accounts
    depends_on:
      consul:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - mba-net
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "server.port":8080,
          "spring.cloud.consul.host":"consul",
          "spring.cloud.consul.port":8500,
          "spring.security.oauth2.client.provider.keycloak.issuer-uri":"http://keycloak:8080/realms/mba",
          "spring.security.oauth2.resourceserver.jwt.issuer-uri":"http://keycloak:8080/realms/mba",
          "spring.datasource.url":"jdbc:postgresql://postgres:5432/accounts_db",
          "spring.datasource.username":"root",
          "spring.datasource.password":"root"
        }
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

networks:
  mba-net: