server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

spring:
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/mba

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - StripPrefix=2
            - TokenRelay=
          routes:
            - id: accounts_service_route
              uri: lb://accounts
              predicates:
                - Path=/api/v1/account/**