server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
    health:
      show-details: always

spring:
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/mma # для TokenRelay
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          default-filters:
            - TokenRelay=
          routes:
            - id: accounts_service_route
              uri: lb://accounts
              predicates:
                - Path=/account/**