server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer_db
    username: root
    password: root
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/mba
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:9090/realms/mba # Адрес сервера авторизации для получения токена
        registration:
          mba-transfer: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: mba-transfer
            client-secret: 0IsHuz83vMySfN7WOTWWLw1zdbzaTyEB
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета